frontend:
  image:
    repository: yonahdissen/kubernetes-access-manager-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []
  resources: {}
  env:
    # Backend API URL - will be set to backend service by default
    apiBaseUrl: "http://kubernetes-access-manager-backend:5005"  # Use the full service name

backend:
  image:
    repository: yonahdissen/kubernetes-access-manager-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5005
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []
  resources: {}

# Common settings
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "kubernetes-access-manager"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 