name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-frontend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata (tags, labels) for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-backend
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

  create-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            ### Frontend
            - Updated to version ${{ github.ref_name }}
            - Docker image: `${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-frontend:${{ github.ref_name }}`
            
            ### Backend
            - Updated to version ${{ github.ref_name }}
            - Docker image: `${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-backend:${{ github.ref_name }}`
            
            ## Installation
            
            ```bash
            # Pull the latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-frontend:${{ github.ref_name }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/kubernetes-access-manager-backend:${{ github.ref_name }}
            
            # Install using Helm
            helm install kubernetes-access-manager ./helm/kubernetes-access-manager \
              --set frontend.image.tag=${{ github.ref_name }} \
              --set backend.image.tag=${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
          generate_release_notes: true 